In [1]:
palabras = ["adidas","colombia","argentina", "brasil", "alemania"]

palabras.pop(-2,) #se esta eliminado un elemento de la lista
palabras.pop(2,)

print(palabras)


['adidas', 'colombia', 'alemania']


In [2]:
palabras = ["hola", "hello", "ciao", "salute", "hello"]

palabras.remove("hello") #se esta eliminado un elemento de la lista
palabras.remove("hola")

print(palabras)#con esto imprime las palabras o elementos que no fueron eliminados

['ciao', 'salute', 'hello']


In [3]:
personas = [
    {"nombre": "Juan", "documento": "12345678"},
    {"nombre": "Ana", "documento": "23456789"},
    {"nombre": "Luis", "documento": "34567890"}
]


for persona in personas:
    print(f"Nombre: {persona['nombre']}, Documento: {persona['documento']}")

Nombre: Juan, Documento: 12345678
Nombre: Ana, Documento: 23456789
Nombre: Luis, Documento: 34567890


In [27]:
# cantidad de personas a ingresar
tamaño = int(input("Ingrese la cantidad de personas: "))

# Inicializamos las listas donde guardaremos los datos
nombres = []
identificaciones = []
direcciones = []

# Bucle para ingresar los datos de cada persona
for i in range(tamaño):
    print("Ingrese los datos de la persona", i + 1)
    nombre = input("Nombre: ")
    identificacion = input("Identificación: ")
    direccion = input("Dirección: ")

    # Guardamos los datos en las listas correspondientes
    nombres.append(nombre)
    identificaciones.append(identificacion)
    direcciones.append(direccion)

# Bucle para mostrar los datos ingresados de cada persona
for i in range(tamaño):
    print("\nMostrando los datos de la persona", i + 1)
    print("Nombre:", nombres[i])
    print("Identificación:", identificaciones[i])
    print("Dirección:", direcciones[i])


Ingrese la cantidad de personas: 1
Ingrese los datos de la persona 1
Nombre: paka
Identificación: 1012357850
Dirección: carrera78c#60-42 sur

Mostrando los datos de la persona 1
Nombre: paka
Identificación: 1012357850
Dirección: carrera78c#60-42 sur


In [28]:


import numpy as np

lst=[10,20,30,40,50]

lst2=['andres','jose','maria','alan','david']

lst3=['melon','lulo','banano','piña','cerezas']

vctr = np.array(lst)

vctr1 = np.array(lst2)

vctr2 = np.array(lst3)


print("Vector created from a list:")
print(vctr)
print(vctr1)
print(vctr2)

Vector created from a list:
[10 20 30 40 50]
['andres' 'jose' 'maria' 'alan' 'david']
['melon' 'lulo' 'banano' 'piña' 'cerezas']


In [18]:
import numpy as np

lst=[[2],[4],[6],[10]]

lst1=[["andres"],["jose"],["maria"],["alan"]]

lst2=[["lulo"],["piña"],["cerezas"],["banana"]]

vctr = np.array(lst)
vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("vector created from a list: ")
print(vctr)

print("vector created from a list: ")
print(vctr1)
print("vector created from a list: ")
print(vctr2)

vector created from a list: 
[[ 2]
 [ 4]
 [ 6]
 [10]]
vector created from a list: 
[['andres']
 ['jose']
 ['maria']
 ['alan']]
vector created from a list: 
[['lulo']
 ['piña']
 ['cerezas']
 ['banana']]


In [20]:
import numpy as np

lst1=[10,20,30,40,50]
lst2=[1,2,3,4,5,6,7]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list:")
print(vctr1)
print("Vector created from a list:")
print(vctr2)

vctr_add=vctr1+vctr2
print("addittion of two vectors: ",vctr_add)


Vector created from a list:
[10 20 30 40 50]
Vector created from a list:
[1 2 3 4 5 6 7]


ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [22]:
import numpy as np

lst1=[10,20,30,40,50]
lst2=[1,2,3,4,5]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list:")
print(vctr1)
print("Vector created from a list:")
print(vctr2)

vctr_add=vctr1-vctr2
print("addittion of two vectors: ",vctr_add)

Vector created from a list:
[10 20 30 40 50]
Vector created from a list:
[1 2 3 4 5]
addittion of two vectors:  [ 9 18 27 36 45]


In [25]:
import numpy as np

lst1=[10,20,30,40,50]
lst2=[1,2,3,4,5]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list:")
print(vctr1)
print("Vector created from a list:")
print(vctr2)

vctr_add=vctr1*vctr2
print("addittion of two vectors: ",vctr_add)

Vector created from a list:
[10 20 30 40 50]
Vector created from a list:
[1 2 3 4 5]
addittion of two vectors:  [ 10  40  90 160 250]


In [26]:
import numpy as np

lst1=[10,20,30,40,50]
lst2=[1,2,3,4,5]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list:")
print(vctr1)
print("Vector created from a list:")
print(vctr2)

vctr_add=vctr1/vctr2
print("addittion of two vectors: ",vctr_add)

Vector created from a list:
[10 20 30 40 50]
Vector created from a list:
[1 2 3 4 5]
addittion of two vectors:  [10. 10. 10. 10. 10.]


In [29]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,1,1,1,1]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado a partir de una lista 1:")
print(vctr1)

print("Vector creado a partir de una lista 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Producto punto de los dos vectores:", vctr_dot)


Vector creado a partir de una lista 1:
[10 20 30 40 50]
Vector creado a partir de una lista 2:
[1 1 1 1 1]
Producto punto de los dos vectores: 150


In [30]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [2,2,2,2,2]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector creado a partir de una lista 1:")
print(vctr1)

print("Vector creado a partir de una lista 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Producto punto de los dos vectores:", vctr_dot)


Vector creado a partir de una lista 1:
[10 20 30 40 50]
Vector creado a partir de una lista 2:
[2 2 2 2 2]
Producto punto de los dos vectores: 300
